### ISSUE TITLE
components.js should be replaced with a call to origami-repo-data

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-component-converter#21]
Using origami-repo-data will ensure that this project is aware of any changes to the list of Origami-core maintained components without having to manually update a file in this repo.

**Comment by chee** [comment]
also, if component `z-dog` depends on `z-cat` and we don't have either of those in `components.json` then during the build of `z-dog` the paths for `z-cat` will not be updated.

**Comment by chee** [comment]
it's possible that Origami Repo Data could keep track of the components that have been published to npm

**Comment by JakeChampion** [comment]
We should do this likely before we create any new components because a new component would not be usable on npm until this project updates it's components/json file or uses origami-repo-data

**Comment by chee** [comment]
100%. It also relates to another wishlist item: https://github.com/Financial-Times/origami-repo-data/issues/103

**Comment by chee** [comment]
@JakeChampion i think that's not quite true, it wouldn't be until an unlisted component depends on a unlisted component that we'd have the problem of it being unuseable.
