### ISSUE TITLE
Prevent use of the incorrect `bower.json` name

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-component-converter#28]
At some point we'll need to make a breaking change to `occ` in order to stop using the potentially-incorrect `name` property of `bower.json`. @chee is adding the ability to specify a component name as well as a version, and deprecating the ability to _not_ pass a component name in.

When we make a breaking change to `occ`, we'll need to go into each component's Circle config and ensure that the correct version is installed.

**Comment by chee** [comment]
oh  [i've done this now](../pulls/30). and [origami-ci](/financial-times/origami-ci-tools) [uses the name](https://github.com/Financial-Times/origami-ci-tools/blob/master/commands/release.js#L11) properly ^_^
