### ISSUE TITLE
Remove commonjs transform

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-component-converter#31]
**After the [major cascade](https://github.com/orgs/Financial-Times/projects/77), when all our components use the esm syntax,** 
remove the [commonjs babel transform](https://github.com/Financial-Times/origami-component-converter/blob/live/lib/babel.js#L37).

Why? The transform uses getters for default exports which may prevent 
sinon stubs from working and cause test [errors for the npm distribution](https://circleci.com/gh/Financial-Times/o-comments/401?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link), 
where the bower distribution passes.
```
Object.defineProperty(exports, "fetchJsonWebToken", {
  enumerable: true,
  get: function get() {
    return _fetchJsonWebToken.default;
  }
});
```

**Comment by notlee** [comment]
We can't do this immediately as we may need to release a patch to a previous major version.

**Comment by JakeChampion** [comment]
@notlee if the components have a pinned version occ then we can do this because the older version of the component will have the older version of occ pinned

**Comment by notlee** [comment]
Oh course!

**Comment by notlee** [comment]
It's not pinned at the moment but I think this would be a major release anyway.
Any reason we haven't published v1 yet?
https://github.com/Financial-Times/origami-ci-tools/blob/16deedfd28db63a47f4f82900d2bd87d45e5ffc1/package.json#L41

**Comment by chee** [comment]
they are using `^0.14`, and this change would be breaking so `0.15` or `1.0` which wouldn't be picked up by `origami-ci`, and we'd then do an `origami-ci` `2.0` release which depends on the new `occ`
